[package]
name = "kinect-control"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.4"
image = "0.24.5"
freenect-sys = { git = "https://github.com/brandonphelps/freenect-sys.git" } 

